### ISSUE TITLE
Relative path names in imports

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/edugis-pwa#6]
https://github.com/Geodan/edugis-pwa/blob/2dbc5f3f9d9eeeb6b72e1c479f58950ea6e17ffc/src/components/map/layer/map-layer.js#L6

**Comment by anneb** [comment]
probably a left-over from Fixed in https://github.com/Geodan/edugis-pwa/commit/55303704b391fdb49724eaed39548f013d826f17
